[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "VictoorLDS", email = "vlds221005@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
