# Generated by Django 4.1.7 on 2023-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='Modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
