# Generated by Django 4.1.7 on 2023-03-31 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_veiculo_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
